import { useAuth } from "@/_core/hooks/useAuth";
import { startLogin } from "@/const";
import { trpc } from "@/lib/trpc";
import { AlertTriangle, ArrowUpRight, Bell, ChevronLeft, ClipboardCheck, Download, FileClock, FileText, GitCommitHorizontal, GitCompareArrows, PackageCheck, RefreshCw, ShieldAlert, ShieldCheck, TriangleAlert } from "lucide-react";
import { FormEvent, useMemo, useState } from "react";
import { Link, useRoute } from "wouter";
import "./PackageDetail.css";
import "./PackageSecurityFlow.css";
import "./PackageStatus.css";

const severityTitle = { low: "Düşük", moderate: "Orta", high: "Yüksek", critical: "Kritik" } as const;

function DetailLoading() {
  return <main className="detail-status-shell"><header><span className="status-wordmark">Nokta <b>Studio</b></span><span>PAKET İNCELEME FÖYÜ</span></header><section><div className="detail-status-mark"><FileText size={24} /></div><p>İZLEK / 01 · PAKET BİLGİSİ</p><h1>İnceleme föyünü<br /><em>açıyoruz.</em></h1><div className="detail-status-trace"><i /><i /><i /><span>README, SÜRÜM VE SAĞLIK KAYDI OKUNUYOR</span></div><small>Paket inceleme sayfası hazırlanıyor…</small></section></main>;
}

export default function PackageDetail() {
  const [, params] = useRoute("/paketler/:packageId");
  const packageId = Number(params?.packageId ?? 0);
  const { user, loading } = useAuth();
  const utils = trpc.useUtils();
  const detail = trpc.packageRegistry.detail.useQuery({ packageId }, { enabled: Boolean(user && packageId) });
  const workspace = trpc.packageRegistry.workspace.useQuery(undefined, { enabled: Boolean(user) });
  const [advisoryDraft, setAdvisoryDraft] = useState({ affectedRange: "*", severity: "moderate" as "low" | "moderate" | "high" | "critical", summary: "", remediation: "" });
  const addAdvisory = trpc.packageRegistry.addSecurityAdvisory.useMutation({ onSuccess: () => { utils.packageRegistry.detail.invalidate({ packageId }); utils.packageRegistry.workspace.invalidate(); utils.packageRegistry.graph.invalidate(); setAdvisoryDraft({ affectedRange: "*", severity: "moderate", summary: "", remediation: "" }); } });
  const install = trpc.packageRegistry.install.useMutation({ onSuccess: () => { utils.packageRegistry.detail.invalidate({ packageId }); utils.packageRegistry.workspace.invalidate(); utils.packageRegistry.graph.invalidate(); } });
  const applyUpdate = trpc.packageRegistry.applyUpdate.useMutation({ onSuccess: () => { utils.packageRegistry.detail.invalidate({ packageId }); utils.packageRegistry.workspace.invalidate(); utils.packageRegistry.graph.invalidate(); } });
  const currentInstallId = detail.data?.currentInstall?.id ?? 0;
  const securityResolution = trpc.packageRegistry.securityResolution.useQuery({ installId: currentInstallId }, { enabled: Boolean(user && currentInstallId) });
  const applySecurityUpdate = trpc.packageRegistry.applySecurityUpdate.useMutation({ onSuccess: () => { utils.packageRegistry.detail.invalidate({ packageId }); utils.packageRegistry.workspace.invalidate(); utils.packageRegistry.graph.invalidate(); utils.packageRegistry.installHistory.invalidate(); } });
  const recordDownloadIntent = trpc.packageRegistry.recordDownloadIntent.useMutation({ onSuccess: () => utils.packageRegistry.installHistory.invalidate() });
  const currentAccess = useMemo(() => detail.data?.registry ? workspace.data?.registries.find((registry) => registry.id === detail.data!.registry!.id)?.access : undefined, [detail.data, workspace.data]);
  const canReport = currentAccess === "owner" || currentAccess === "publisher";
  const submitAdvisory = (event: FormEvent) => { event.preventDefault(); addAdvisory.mutate({ packageId, ...advisoryDraft }); };

  if (loading) return <DetailLoading />;
  if (!user) return <main className="detail-auth"><PackageCheck size={32} /><h1>Paket incelemesi için oturum açın.</h1><p>Özel ve kurumsal paket ayrıntıları, erişim sınırları korunarak gösterilir.</p><button onClick={() => startLogin()}><ShieldCheck size={15} /> Oturum aç</button><Link href="/paketler"><ChevronLeft size={15} /> Kayıt merkezine dön</Link></main>;
  if (detail.isLoading) return <main className="detail-loading">Paket verisi okunuyor…</main>;
  if (!detail.data) return <main className="detail-loading"><AlertTriangle size={21} /> {detail.error?.message || "Paket ayrıntısı bulunamadı."}<Link href="/paketler">Kayıt merkezine dön</Link></main>;

  const { package: pkg, registry, versions, advisories, usage, currentInstall } = detail.data;
  const latest = versions[0];
  return <main className="detail-shell">
    <header className="detail-topbar"><Link href="/paketler"><ChevronLeft size={16} /> Kayıt merkezi</Link><span>{registry?.displayName} · {registry?.visibility === "private" ? "ÖZEL KAYIT" : "KURUMSAL KAYIT"}</span></header>
    <section className="detail-hero"><div><p className="eyebrow">PAKET İNCELEMESİ</p><div className="detail-title-line"><h1>{pkg.name}</h1>{advisories.length > 0 && <span className={`detail-severity ${advisories[0].severity}`}><ShieldAlert size={13} /> {severityTitle[advisories[0].severity]}</span>}</div><p>{pkg.description || "Bu paket için açıklama yayımlanmadı."}</p><div className="detail-meta"><span>v{pkg.latestVersion || "—"}</span><span>{registry?.slug}</span><span>{versions.length} sürüm</span></div></div><div className="detail-actions">{currentInstall ? <><span><ClipboardCheck size={14} /> {currentInstall.lockedVersion} kilitli</span>{securityResolution.data?.affected.length && securityResolution.data.recommendation ? <button className="security-action" onClick={() => applySecurityUpdate.mutate({ installId: currentInstall.id })}><ShieldAlert size={14} /> v{securityResolution.data.recommendation.version} ile güvenli güncelle</button> : currentInstall.updateAvailable && <button onClick={() => applyUpdate.mutate({ installId: currentInstall.id })}><RefreshCw size={14} /> Güncellemeyi uygula</button>}</> : latest && <button onClick={() => install.mutate({ packageId: pkg.id, requestedRange: `^${latest.version.split(".").slice(0, 2).join(".")}` })}><Download size={14} /> Paketi kur</button>}{latest && <button className="download-intent" onClick={() => recordDownloadIntent.mutate({ packageId: pkg.id })}><Download size={13} /> İndirme isteğini kaydet</button>}</div></section>
    <section className="detail-metrics"><article><PackageCheck size={16} /><span>Aktif kurulum</span><strong>{usage.installations}</strong></article><article><RefreshCw size={16} /><span>Güncelleme bekliyor</span><strong>{usage.updatesPending}</strong></article><article><GitCommitHorizontal size={16} /><span>Yayımlanmış sürüm</span><strong>{versions.length}</strong></article><article><ShieldAlert size={16} /><span>Açık uyarı</span><strong>{advisories.length}</strong></article></section>
    <section className="detail-grid"><article className="detail-paper readme-paper"><div className="detail-heading"><span><FileText size={14} /> README</span><small>PAKET BELGESİ</small></div>{pkg.readme ? <pre>{pkg.readme}</pre> : <div className="detail-empty"><FileText size={23} /><strong>README henüz yayımlanmadı.</strong><span>Yayıncı, bir sonraki sürümde kullanım belgelerini ekleyebilir.</span></div>}</article><aside className="detail-paper health-paper"><div className="detail-heading"><span><ShieldAlert size={14} /> PAKET SAĞLIĞI</span><small>GERÇEK UYARILAR</small></div>{securityResolution.data?.affected.length ? <div className="security-resolution"><span>ÇÖZÜM ÖNERİSİ</span><strong>v{securityResolution.data.currentVersion} sürümünde {securityResolution.data.affected.length} açık uyarı var.</strong>{securityResolution.data.recommendation ? <p>Önerilen güvenli sürüm: <b>v{securityResolution.data.recommendation.version}</b></p> : <p>Bu sürüm aralığında güvenli bir güncelleme bulunamadı; yayıncı giderme önerisini izleyin.</p>}</div> : null}{advisories.length ? <div className="advisory-list">{advisories.map((advisory) => <article key={advisory.id} className={`advisory ${advisory.severity}`}><div><span>{severityTitle[advisory.severity]}</span><small>{advisory.affectedRange} etkileniyor</small></div><strong>{advisory.summary}</strong>{advisory.remediation && <p>Öneri: {advisory.remediation}</p>}</article>)}</div> : <div className="detail-empty"><ShieldCheck size={23} /><strong>Açık güvenlik uyarısı yok.</strong><span>Bu kayıt için doğrulanmış aktif bir sağlık bildirimi bulunmuyor.</span></div>}</aside></section>
    <section className="detail-grid history-grid"><article className="detail-paper"><div className="detail-heading"><span><GitCommitHorizontal size={14} /> SÜRÜM GEÇMİŞİ</span><small><Link className="detail-link" href={`/paketler/${pkg.id}/karsilastir`}><GitCompareArrows size={11} /> SÜRÜMLERİ KARŞILAŞTIR</Link></small></div><div className="version-history">{versions.map((version, index) => <article key={version.id}><span className="version-trace"><i />{index + 1}</span><div><strong>v{version.version}</strong><small>{new Date(version.publishedAt).toLocaleString("tr-TR")}</small>{version.releaseNotes && <p>{version.releaseNotes}</p>}<code>{version.integrity}</code></div><aside><b>{version.entry}</b><span>{version.exports.join(", ") || "Dışa aktarım yok"}</span>{Object.keys(version.dependencies).length > 0 && <span>{Object.entries(version.dependencies).map(([name, range]) => `${name}@${range}`).join(" · ")}</span>}</aside></article>)}</div></article><aside className="detail-paper health-form-paper">{canReport ? <><div className="detail-heading"><span><TriangleAlert size={14} /> UYARI BİLDİR</span><small>YAYINCI YETKİSİ</small></div><form onSubmit={submitAdvisory} className="advisory-form"><label>Etkilenen sürüm aralığı<input required value={advisoryDraft.affectedRange} onChange={(event) => setAdvisoryDraft({ ...advisoryDraft, affectedRange: event.target.value })} placeholder="^1.2" /></label><label>Önem<select value={advisoryDraft.severity} onChange={(event) => setAdvisoryDraft({ ...advisoryDraft, severity: event.target.value as typeof advisoryDraft.severity })}><option value="low">Düşük</option><option value="moderate">Orta</option><option value="high">Yüksek</option><option value="critical">Kritik</option></select></label><label>Kısa açıklama<input required value={advisoryDraft.summary} onChange={(event) => setAdvisoryDraft({ ...advisoryDraft, summary: event.target.value })} placeholder="Etkilenen davranış" /></label><label>Giderme önerisi<textarea value={advisoryDraft.remediation} onChange={(event) => setAdvisoryDraft({ ...advisoryDraft, remediation: event.target.value })} placeholder="Güncelleme veya geçici çözüm" /></label><button disabled={addAdvisory.isPending}>{addAdvisory.isPending ? "Kaydediliyor" : "Uyarıyı kaydet"}</button></form></> : <div className="detail-empty"><Bell size={23} /><strong>Sağlık bildirimi yayıncıya açıktır.</strong><span>Okuyucular doğrulanmış uyarıları ve giderme önerilerini burada inceleyebilir.</span></div>}<Link className="detail-history-link" href="/paketler/gecmis"><FileClock size={13} /> İzinli işlem günlüğü</Link></aside></section>
  </main>;
}
