import { mkdir, mkdtemp, readFile, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { spawn } from "node:child_process";

const root = await mkdtemp(join(tmpdir(), "nokta-helper-"));
const home = join(root, "home");
const workspace = join(root, "workspace");
const port = 18417;
const origin = "https://boyleiyi620-hue.github.io";
await mkdir(home, { recursive: true });
await writeFile(join(home, "config.json"), JSON.stringify({ version: 2, workspace, maximumBytes: 5 * 1024 * 1024, allowedOrigins: [origin], https: {} }));
const child = spawn(process.execPath, ["src/server.mjs"], { cwd: new URL("..", import.meta.url), env: { ...process.env, NOKTA_HELPER_HOME: home, NOKTA_HELPER_PORT: String(port), NOKTA_HELPER_ALLOW_HTTP_TESTS: "1" }, stdio: ["ignore", "pipe", "pipe"] });
let output = "";
let errorOutput = "";
child.stdout.on("data", (chunk) => { output += chunk; });
child.stderr.on("data", (chunk) => { errorOutput += chunk; });
await new Promise((resolve, reject) => {
  const timeout = setTimeout(() => reject(new Error(`Yardımcı başlamadı: ${output}\n${errorOutput}`)), 4000);
  child.stdout.on("data", () => { if (output.includes("Nokta Yardımcı hazır") && output.includes("Eşleştirme kodu")) { clearTimeout(timeout); resolve(); } });
});
const pairingCode = output.match(/Eşleştirme kodu \(5 dakika geçerli\): ([^\s]+)/)?.[1];
if (!pairingCode) throw new Error("Eşleştirme kodu bulunamadı.");
const request = (path, options = {}) => fetch(`http://127.0.0.1:${port}${path}`, { ...options, headers: { Origin: origin, ...(options.headers ?? {}) } });
const hostile = await fetch(`http://127.0.0.1:${port}/v1/pair`, { method: "POST", headers: { Origin: "https://ornek-kotu.site", "X-Nokta-Pairing-Code": pairingCode } });
if (hostile.status !== 403) throw new Error("İzinli olmayan kaynak engellenmedi.");
const pairing = await request("/v1/pair", { method: "POST", headers: { "X-Nokta-Pairing-Code": pairingCode } });
const pairBody = await pairing.json();
if (!pairing.ok || !pairBody.sessionToken) throw new Error(JSON.stringify(pairBody));
const headers = { "Content-Type": "application/json", "X-Nokta-Session": pairBody.sessionToken };
const plan = { taskId: "smoke_001", idempotencyKey: "smoke_key_001", expiresAt: new Date(Date.now() + 60_000).toISOString(), actions: [{ type: "file.mkdir", path: "girdi" }, { type: "file.write", path: "girdi/ornek.csv", content: "ad,tutar\nAda,1200" }, { type: "file.read", path: "girdi/ornek.csv" }, { type: "file.list", path: "girdi" }] };
const response = await request("/v1/plans/execute", { method: "POST", headers, body: JSON.stringify(plan) });
const body = await response.json();
if (!response.ok || body.receipt?.results?.[2]?.content !== "ad,tutar\nAda,1200" || body.receipt?.results?.[3]?.entries?.[0]?.name !== "ornek.csv") throw new Error(JSON.stringify(body));
const saved = await readFile(join(workspace, "girdi", "ornek.csv"), "utf8");
if (saved !== "ad,tutar\nAda,1200") throw new Error("Dosya içeriği beklenen değerde değil.");
const replay = await request("/v1/plans/execute", { method: "POST", headers, body: JSON.stringify(plan) });
if (!(await replay.json()).reused) throw new Error("Yinelenen plan makbuzu yeniden kullanılamadı.");
const unsafePlan = { taskId: "smoke_002", idempotencyKey: "smoke_key_002", expiresAt: new Date(Date.now() + 60_000).toISOString(), actions: [{ type: "file.write", path: "../disari.json", content: "{}" }] };
const unsafe = await request("/v1/plans/execute", { method: "POST", headers, body: JSON.stringify(unsafePlan) });
if (unsafe.status !== 400) throw new Error("Çalışma klasörü dışına taşma planı reddedilmedi.");
child.kill("SIGTERM");
await rm(root, { recursive: true, force: true });
console.log("HTTPS eşleştirme ve Windows dosya bağdaştırıcısı smoke testi geçti.");
